package com.yinhan.surface;

import com.yinhan.data.TestCaseBean;

public class  PanelBean extends javax.swing.JPanel {
	
    public TestCaseBean getTestcaseBean() {
		return testcaseBean;
	}


	public void setTestcaseBean(TestCaseBean testcaseBean) {
		this.testcaseBean = testcaseBean;
		
	}

	private javax.swing.JTextField DescTextField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JButton actionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private TestCaseBean testcaseBean;
    
    private ActionResultSur actionsur;

    /**
     * Creates new form PanelBean
     */
    public PanelBean() {
    }

  
    public void updateData()
    {
    	testcaseBean.setId(IDTextField.getText());
    	testcaseBean.setInstruction(DescTextField.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DescTextField = new javax.swing.JTextField();
        actionBtn = new javax.swing.JButton();

        jLabel1.setText("序号");
        
        if(testcaseBean==null)
        {
        	   IDTextField.setText("ID");
        }else
        {
        	IDTextField.setText(testcaseBean.getId());
        }
     

        jLabel2.setText("描述");
        if(testcaseBean==null)
        {
        	 DescTextField.setText("description");
        }else
        {
        	 DescTextField.setText(testcaseBean.getInstruction());
        }
        

       

        actionBtn.setText("动作和结果");
        actionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(DescTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(actionBtn)
                    .addContainerGap())
            );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(DescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void actionBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	
    	if(actionsur == null)
    	{
    		actionsur = new ActionResultSur(testcaseBean);
    	}
    	actionsur.setTempPanelBean(this);
    	actionsur.setVisible(true);
    }
                            


                 
}
